export const ADD_FAV = 'ADD_FAV';
export const REMOVE_FAV = 'REMOVE_FAV';
export const FILTER = 'FILTER';
export const ORDER = 'ORDER';
export const ADD_CHARACTER = 'ADD_CHARACTER';
export const REMOVE_CHARACTER = 'REMOVE_CHARACTER'
export const CLEAN_CHARACTERS = 'CLEAN_CHARACTERS'
export const ADD_LOCAL_STORAGE_CHARACTERS = 'ADD_LOCAL_STORAGE_CHARACTERS';